<?xml version="1.0" encoding="UTF-8"?>
<!--
  Author: David Klingenberg
  Date: 02/22/2014
-->


<!DOCTYPE map [
  <!ELEMENT map (hex)>
  <!ELEMENT hex (id, nid, neid, seid, sid, swid, nwid, scode?)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT nid (#PCDATA)>
  <!ELEMENT neid (#PCDATA)>
  <!ELEMENT seid (#PCDATA)>
  <!ELEMENT sid (#PCDATA)>
  <!ELEMENT swid (#PCDATA)>
  <!ELEMENT nwid (#PCDATA)>
  <!ELEMENT scode (#PCDATA)>
]>


<map>
  <hex>
    <id>0104</id>
    <nid>0</nid>
    <neid>0203</neid>
    <seid>0204</seid>
    <sid>0105</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>1</scode>
  </hex>
  <hex>
    <id>0105</id>
    <nid>0104</nid>
    <neid>0204</neid>
    <seid>0205</seid>
    <sid>0106</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0106</id>
    <nid>0105</nid>
    <neid>0205</neid>
    <seid>0206</seid>
    <sid>0107</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0107</id>
    <nid>0106</nid>
    <neid>0206</neid>
    <seid>0207</seid>
    <sid>0108</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0108</id>
    <nid>0107</nid>
    <neid>0207</neid>
    <seid>0208</seid>
    <sid>0109</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0109</id>
    <nid>0108</nid>
    <neid>0208</neid>
    <seid>0209</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0</nwid>
    <scode>1</scode>
  </hex>
  <hex>
    <id>0203</id>
    <nid>0</nid>
    <neid>0303</neid>
    <seid>0304</seid>
    <sid>0204</sid>
    <swid>0104</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0204</id>
    <nid>0203</nid>
    <neid>0304</neid>
    <seid>0305</seid>
    <sid>0205</sid>
    <swid>0105</swid>
    <nwid>0104</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0205</id>
    <nid>0204</nid>
    <neid>0305</neid>
    <seid>0306</seid>
    <sid>0206</sid>
    <swid>0106</swid>
    <nwid>0105</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0206</id>
    <nid>0205</nid>
    <neid>0306</neid>
    <seid>0307</seid>
    <sid>0207</sid>
    <swid>0107</swid>
    <nwid>0106</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0207</id>
    <nid>0206</nid>
    <neid>0307</neid>
    <seid>0308</seid>
    <sid>0208</sid>
    <swid>0108</swid>
    <nwid>0107</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0208</id>
    <nid>0207</nid>
    <neid>0308</neid>
    <seid>0309</seid>
    <sid>0209</sid>
    <swid>0109</swid>
    <nwid>0108</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0209</id>
    <nid>0208</nid>
    <neid>0309</neid>
    <seid>0310</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0109</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0303</id>
    <nid>0</nid>
    <neid>0402</neid>
    <seid>0403</seid>
    <sid>0304</sid>
    <swid>0203</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0304</id>
    <nid>0303</nid>
    <neid>0403</neid>
    <seid>0404</seid>
    <sid>0305</sid>
    <swid>0204</swid>
    <nwid>0203</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0305</id>
    <nid>0304</nid>
    <neid>0404</neid>
    <seid>0405</seid>
    <sid>0306</sid>
    <swid>0205</swid>
    <nwid>0204</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0306</id>
    <nid>0305</nid>
    <neid>0405</neid>
    <seid>0406</seid>
    <sid>0307</sid>
    <swid>0206</swid>
    <nwid>0205</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0307</id>
    <nid>0306</nid>
    <neid>0406</neid>
    <seid>0407</seid>
    <sid>0308</sid>
    <swid>0207</swid>
    <nwid>0206</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0308</id>
    <nid>0307</nid>
    <neid>0407</neid>
    <seid>0408</seid>
    <sid>0309</sid>
    <swid>0208</swid>
    <nwid>0207</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0309</id>
    <nid>0308</nid>
    <neid>0408</neid>
    <seid>0409</seid>
    <sid>0310</sid>
    <swid>0209</swid>
    <nwid>0208</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0310</id>
    <nid>0309</nid>
    <neid>0409</neid>
    <seid>0410</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0209</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0402</id>
    <nid>0</nid>
    <neid>0502</neid>
    <seid>0503</seid>
    <sid>0403</sid>
    <swid>0303</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0403</id>
    <nid>0402</nid>
    <neid>0503</neid>
    <seid>0504</seid>
    <sid>0404</sid>
    <swid>0304</swid>
    <nwid>0303</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0404</id>
    <nid>0403</nid>
    <neid>0504</neid>
    <seid>0505</seid>
    <sid>0405</sid>
    <swid>0305</swid>
    <nwid>0304</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0405</id>
    <nid>0404</nid>
    <neid>0505</neid>
    <seid>0506</seid>
    <sid>0406</sid>
    <swid>0306</swid>
    <nwid>0305</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0406</id>
    <nid>0405</nid>
    <neid>0506</neid>
    <seid>0507</seid>
    <sid>0407</sid>
    <swid>0307</swid>
    <nwid>0306</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0407</id>
    <nid>0406</nid>
    <neid>0507</neid>
    <seid>0508</seid>
    <sid>0408</sid>
    <swid>0308</swid>
    <nwid>0307</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0408</id>
    <nid>0407</nid>
    <neid>0508</neid>
    <seid>0509</seid>
    <sid>0409</sid>
    <swid>0309</swid>
    <nwid>0308</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0409</id>
    <nid>0408</nid>
    <neid>0509</neid>
    <seid>0510</seid>
    <sid>0410</sid>
    <swid>0310</swid>
    <nwid>0309</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0410</id>
    <nid>0409</nid>
    <neid>0510</neid>
    <seid>0511</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0310</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0502</id>
    <nid>0</nid>
    <neid>0601</neid>
    <seid>0602</seid>
    <sid>0503</sid>
    <swid>0402</swid>
    <nwid>0</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0503</id>
    <nid>0502</nid>
    <neid>0602</neid>
    <seid>0603</seid>
    <sid>0504</sid>
    <swid>0403</swid>
    <nwid>0402</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0504</id>
    <nid>0503</nid>
    <neid>0603</neid>
    <seid>0604</seid>
    <sid>0505</sid>
    <swid>0404</swid>
    <nwid>0403</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0505</id>
    <nid>0504</nid>
    <neid>0604</neid>
    <seid>0605</seid>
    <sid>0506</sid>
    <swid>0405</swid>
    <nwid>0404</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0506</id>
    <nid>0505</nid>
    <neid>0605</neid>
    <seid>0606</seid>
    <sid>0507</sid>
    <swid>0406</swid>
    <nwid>0405</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0507</id>
    <nid>0506</nid>
    <neid>0606</neid>
    <seid>0607</seid>
    <sid>0508</sid>
    <swid>0407</swid>
    <nwid>0406</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0508</id>
    <nid>0507</nid>
    <neid>0607</neid>
    <seid>0608</seid>
    <sid>0509</sid>
    <swid>0408</swid>
    <nwid>0407</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0509</id>
    <nid>0508</nid>
    <neid>0608</neid>
    <seid>0609</seid>
    <sid>0510</sid>
    <swid>0409</swid>
    <nwid>0408</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0510</id>
    <nid>0509</nid>
    <neid>0609</neid>
    <seid>0610</seid>
    <sid>0511</sid>
    <swid>0410</swid>
    <nwid>0409</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0511</id>
    <nid>0510</nid>
    <neid>0610</neid>
    <seid>0611</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0410</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0601</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>0702</seid>
    <sid>0602</sid>
    <swid>0502</swid>
    <nwid>0</nwid>
    <scode>1</scode>
  </hex>
  <hex>
    <id>0602</id>
    <nid>0601</nid>
    <neid>0702</neid>
    <seid>0703</seid>
    <sid>0603</sid>
    <swid>0503</swid>
    <nwid>0502</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0603</id>
    <nid>0602</nid>
    <neid>0703</neid>
    <seid>0704</seid>
    <sid>0604</sid>
    <swid>0504</swid>
    <nwid>0503</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0604</id>
    <nid>0603</nid>
    <neid>0704</neid>
    <seid>0705</seid>
    <sid>0605</sid>
    <swid>0505</swid>
    <nwid>0504</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0605</id>
    <nid>0604</nid>
    <neid>0705</neid>
    <seid>0706</seid>
    <sid>0606</sid>
    <swid>0506</swid>
    <nwid>0505</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0606</id>
    <nid>0605</nid>
    <neid>0706</neid>
    <seid>0707</seid>
    <sid>0607</sid>
    <swid>0507</swid>
    <nwid>0506</nwid>
    <scode>2</scode>
  </hex>
  <hex>
    <id>0607</id>
    <nid>0606</nid>
    <neid>0707</neid>
    <seid>0708</seid>
    <sid>0608</sid>
    <swid>0508</swid>
    <nwid>0507</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0608</id>
    <nid>0607</nid>
    <neid>0708</neid>
    <seid>0709</seid>
    <sid>0609</sid>
    <swid>0509</swid>
    <nwid>0508</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0609</id>
    <nid>0608</nid>
    <neid>0709</neid>
    <seid>0710</seid>
    <sid>0610</sid>
    <swid>0510</swid>
    <nwid>0509</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0610</id>
    <nid>0609</nid>
    <neid>0710</neid>
    <seid>0711</seid>
    <sid>0611</sid>
    <swid>0511</swid>
    <nwid>0510</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0611</id>
    <nid>0610</nid>
    <neid>0711</neid>
    <seid>0</seid>
    <sid>0</sid>
    <swid>0</swid>
    <nwid>0511</nwid>
    <scode>1</scode>
  </hex>
  <hex>
    <id>0702</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>0802</seid>
    <sid>0703</sid>
    <swid>0602</swid>
    <nwid>0601</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0703</id>
    <nid>0702</nid>
    <neid>0802</neid>
    <seid>0803</seid>
    <sid>0704</sid>
    <swid>0603</swid>
    <nwid>0602</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0704</id>
    <nid>0703</nid>
    <neid>0803</neid>
    <seid>0804</seid>
    <sid>0705</sid>
    <swid>0604</swid>
    <nwid>0603</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0705</id>
    <nid>0704</nid>
    <neid>0804</neid>
    <seid>0805</seid>
    <sid>0706</sid>
    <swid>0605</swid>
    <nwid>0604</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0706</id>
    <nid>0705</nid>
    <neid>0805</neid>
    <seid>0806</seid>
    <sid>0707</sid>
    <swid>0606</swid>
    <nwid>0605</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0707</id>
    <nid>0706</nid>
    <neid>0806</neid>
    <seid>0807</seid>
    <sid>0708</sid>
    <swid>0607</swid>
    <nwid>0606</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0708</id>
    <nid>0707</nid>
    <neid>0807</neid>
    <seid>0808</seid>
    <sid>0709</sid>
    <swid>0608</swid>
    <nwid>0607</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0709</id>
    <nid>0708</nid>
    <neid>0808</neid>
    <seid>0809</seid>
    <sid>0710</sid>
    <swid>0609</swid>
    <nwid>0608</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0710</id>
    <nid>0709</nid>
    <neid>0809</neid>
    <seid>0810</seid>
    <sid>0711</sid>
    <swid>0610</swid>
    <nwid>0609</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0711</id>
    <nid>0710</nid>
    <neid>0810</neid>
    <seid>0</seid>
    <sid>0</sid>
    <swid>0611</swid>
    <nwid>0610</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0802</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>0903</seid>
    <sid>0803</sid>
    <swid>0703</swid>
    <nwid>0702</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0803</id>
    <nid>0802</nid>
    <neid>0903</neid>
    <seid>0904</seid>
    <sid>0804</sid>
    <swid>0704</swid>
    <nwid>0703</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0804</id>
    <nid>0803</nid>
    <neid>0904</neid>
    <seid>0905</seid>
    <sid>0805</sid>
    <swid>0705</swid>
    <nwid>0704</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0805</id>
    <nid>0804</nid>
    <neid>0905</neid>
    <seid>0906</seid>
    <sid>0806</sid>
    <swid>0706</swid>
    <nwid>0705</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0806</id>
    <nid>0805</nid>
    <neid>0906</neid>
    <seid>0907</seid>
    <sid>0807</sid>
    <swid>0707</swid>
    <nwid>0706</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0807</id>
    <nid>0806</nid>
    <neid>0907</neid>
    <seid>0908</seid>
    <sid>0808</sid>
    <swid>0708</swid>
    <nwid>0707</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0808</id>
    <nid>0807</nid>
    <neid>0908</neid>
    <seid>0909</seid>
    <sid>0809</sid>
    <swid>0709</swid>
    <nwid>0708</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0809</id>
    <nid>0808</nid>
    <neid>0909</neid>
    <seid>0910</seid>
    <sid>0810</sid>
    <swid>0710</swid>
    <nwid>0709</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0810</id>
    <nid>0809</nid>
    <neid>0910</neid>
    <seid>0</seid>
    <sid>0</sid>
    <swid>0711</swid>
    <nwid>0710</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0811</id>
    <nid>0810</nid>
    <neid>0911</neid>
    <seid>0912</seid>
    <sid>0812</sid>
    <swid>0712</swid>
    <nwid>0711</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0903</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>1003</seid>
    <sid>0904</sid>
    <swid>0803</swid>
    <nwid>0802</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0904</id>
    <nid>0903</nid>
    <neid>1003</neid>
    <seid>1004</seid>
    <sid>0905</sid>
    <swid>0804</swid>
    <nwid>0803</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0905</id>
    <nid>0904</nid>
    <neid>1004</neid>
    <seid>1005</seid>
    <sid>0906</sid>
    <swid>0805</swid>
    <nwid>0804</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0906</id>
    <nid>0905</nid>
    <neid>1005</neid>
    <seid>1006</seid>
    <sid>0907</sid>
    <swid>0806</swid>
    <nwid>0805</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0907</id>
    <nid>0906</nid>
    <neid>1006</neid>
    <seid>1007</seid>
    <sid>0908</sid>
    <swid>0807</swid>
    <nwid>0806</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0908</id>
    <nid>0907</nid>
    <neid>1007</neid>
    <seid>1008</seid>
    <sid>0909</sid>
    <swid>0808</swid>
    <nwid>0807</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0909</id>
    <nid>0908</nid>
    <neid>1008</neid>
    <seid>1009</seid>
    <sid>0910</sid>
    <swid>0809</swid>
    <nwid>0808</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>0910</id>
    <nid>0909</nid>
    <neid>1009</neid>
    <seid>0</seid>
    <sid>0</sid>
    <swid>0810</swid>
    <nwid>0809</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1003</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>1104</seid>
    <sid>1004</sid>
    <swid>0904</swid>
    <nwid>0903</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1004</id>
    <nid>1003</nid>
    <neid>1104</neid>
    <seid>1105</seid>
    <sid>1005</sid>
    <swid>0905</swid>
    <nwid>0904</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1005</id>
    <nid>1004</nid>
    <neid>1105</neid>
    <seid>1106</seid>
    <sid>1006</sid>
    <swid>0906</swid>
    <nwid>0905</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1006</id>
    <nid>1005</nid>
    <neid>1106</neid>
    <seid>1107</seid>
    <sid>1007</sid>
    <swid>0907</swid>
    <nwid>0906</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1007</id>
    <nid>1006</nid>
    <neid>1107</neid>
    <seid>1108</seid>
    <sid>1008</sid>
    <swid>0908</swid>
    <nwid>0907</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1008</id>
    <nid>1007</nid>
    <neid>1108</neid>
    <seid>1109</seid>
    <sid>1009</sid>
    <swid>0909</swid>
    <nwid>0908</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1009</id>
    <nid>1008</nid>
    <neid>1109</neid>
    <seid>1110</seid>
    <sid>0</sid>
    <swid>0910</swid>
    <nwid>0909</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1104</id>
    <nid>0</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>1105</sid>
    <swid>1004</swid>
    <nwid>1003</nwid>
    <scode>1</scode>
  </hex>
  <hex>
    <id>1105</id>
    <nid>1104</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>1106</sid>
    <swid>1005</swid>
    <nwid>1004</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1106</id>
    <nid>1105</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>1107</sid>
    <swid>1006</swid>
    <nwid>1005</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1107</id>
    <nid>1106</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>1108</sid>
    <swid>1007</swid>
    <nwid>1006</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1108</id>
    <nid>1107</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>1109</sid>
    <swid>1008</swid>
    <nwid>1007</nwid>
    <scode>0</scode>
  </hex>
  <hex>
    <id>1109</id>
    <nid>1108</nid>
    <neid>0</neid>
    <seid>0</seid>
    <sid>0</sid>
    <swid>1009</swid>
    <nwid>1008</nwid>
    <scode>1</scode>
  </hex>
</map>
