<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file was auto generated by BuildDiplomacyMapFile.java

  Author: David Klingenberg
  Auto generated on: 2014/03/06 12:10:21
-->


<!DOCTYPE map [
  <!ELEMENT map (hex*)>
  <!ELEMENT hex (hexNumber, northHexNumber, northEastHexNumber, southEastHexNumber, southHexNumber, southWestHexNumber, northWestHexNumber, specialHex?)>
  <!ELEMENT hexNumber (#PCDATA)>
  <!ELEMENT northHexNumber (#PCDATA)>
  <!ELEMENT northEastHexNumber (#PCDATA)>
  <!ELEMENT southEastHexNumber (#PCDATA)>
  <!ELEMENT southHexNumber (#PCDATA)>
  <!ELEMENT southWestHexNumber (#PCDATA)>
  <!ELEMENT northWestHexNumber (#PCDATA)>
  <!ELEMENT specialHex (#PCDATA)>
]>


<map>
  <hex>
    <hexNumber>0104</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0203</northEastHexNumber>
    <southEastHexNumber>0204</southEastHexNumber>
    <southHexNumber>0105</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>1</specialHex>
  </hex>
  <hex>
    <hexNumber>0105</hexNumber>
    <northHexNumber>0104</northHexNumber>
    <northEastHexNumber>0204</northEastHexNumber>
    <southEastHexNumber>0205</southEastHexNumber>
    <southHexNumber>0106</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0106</hexNumber>
    <northHexNumber>0105</northHexNumber>
    <northEastHexNumber>0205</northEastHexNumber>
    <southEastHexNumber>0206</southEastHexNumber>
    <southHexNumber>0107</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0107</hexNumber>
    <northHexNumber>0106</northHexNumber>
    <northEastHexNumber>0206</northEastHexNumber>
    <southEastHexNumber>0207</southEastHexNumber>
    <southHexNumber>0108</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0108</hexNumber>
    <northHexNumber>0107</northHexNumber>
    <northEastHexNumber>0207</northEastHexNumber>
    <southEastHexNumber>0208</southEastHexNumber>
    <southHexNumber>0109</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0109</hexNumber>
    <northHexNumber>0108</northHexNumber>
    <northEastHexNumber>0208</northEastHexNumber>
    <southEastHexNumber>0209</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>1</specialHex>
  </hex>
  <hex>
    <hexNumber>0203</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0303</northEastHexNumber>
    <southEastHexNumber>0304</southEastHexNumber>
    <southHexNumber>0204</southHexNumber>
    <southWestHexNumber>0104</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0204</hexNumber>
    <northHexNumber>0203</northHexNumber>
    <northEastHexNumber>0304</northEastHexNumber>
    <southEastHexNumber>0305</southEastHexNumber>
    <southHexNumber>0205</southHexNumber>
    <southWestHexNumber>0105</southWestHexNumber>
    <northWestHexNumber>0104</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0205</hexNumber>
    <northHexNumber>0204</northHexNumber>
    <northEastHexNumber>0305</northEastHexNumber>
    <southEastHexNumber>0306</southEastHexNumber>
    <southHexNumber>0206</southHexNumber>
    <southWestHexNumber>0106</southWestHexNumber>
    <northWestHexNumber>0105</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0206</hexNumber>
    <northHexNumber>0205</northHexNumber>
    <northEastHexNumber>0306</northEastHexNumber>
    <southEastHexNumber>0307</southEastHexNumber>
    <southHexNumber>0207</southHexNumber>
    <southWestHexNumber>0107</southWestHexNumber>
    <northWestHexNumber>0106</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0207</hexNumber>
    <northHexNumber>0206</northHexNumber>
    <northEastHexNumber>0307</northEastHexNumber>
    <southEastHexNumber>0308</southEastHexNumber>
    <southHexNumber>0208</southHexNumber>
    <southWestHexNumber>0108</southWestHexNumber>
    <northWestHexNumber>0107</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0208</hexNumber>
    <northHexNumber>0207</northHexNumber>
    <northEastHexNumber>0308</northEastHexNumber>
    <southEastHexNumber>0309</southEastHexNumber>
    <southHexNumber>0209</southHexNumber>
    <southWestHexNumber>0109</southWestHexNumber>
    <northWestHexNumber>0108</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0209</hexNumber>
    <northHexNumber>0208</northHexNumber>
    <northEastHexNumber>0309</northEastHexNumber>
    <southEastHexNumber>0310</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0109</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0303</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0402</northEastHexNumber>
    <southEastHexNumber>0403</southEastHexNumber>
    <southHexNumber>0304</southHexNumber>
    <southWestHexNumber>0203</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0304</hexNumber>
    <northHexNumber>0303</northHexNumber>
    <northEastHexNumber>0403</northEastHexNumber>
    <southEastHexNumber>0404</southEastHexNumber>
    <southHexNumber>0305</southHexNumber>
    <southWestHexNumber>0204</southWestHexNumber>
    <northWestHexNumber>0203</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0305</hexNumber>
    <northHexNumber>0304</northHexNumber>
    <northEastHexNumber>0404</northEastHexNumber>
    <southEastHexNumber>0405</southEastHexNumber>
    <southHexNumber>0306</southHexNumber>
    <southWestHexNumber>0205</southWestHexNumber>
    <northWestHexNumber>0204</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0306</hexNumber>
    <northHexNumber>0305</northHexNumber>
    <northEastHexNumber>0405</northEastHexNumber>
    <southEastHexNumber>0406</southEastHexNumber>
    <southHexNumber>0307</southHexNumber>
    <southWestHexNumber>0206</southWestHexNumber>
    <northWestHexNumber>0205</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0307</hexNumber>
    <northHexNumber>0306</northHexNumber>
    <northEastHexNumber>0406</northEastHexNumber>
    <southEastHexNumber>0407</southEastHexNumber>
    <southHexNumber>0308</southHexNumber>
    <southWestHexNumber>0207</southWestHexNumber>
    <northWestHexNumber>0206</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0308</hexNumber>
    <northHexNumber>0307</northHexNumber>
    <northEastHexNumber>0407</northEastHexNumber>
    <southEastHexNumber>0408</southEastHexNumber>
    <southHexNumber>0309</southHexNumber>
    <southWestHexNumber>0208</southWestHexNumber>
    <northWestHexNumber>0207</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0309</hexNumber>
    <northHexNumber>0308</northHexNumber>
    <northEastHexNumber>0408</northEastHexNumber>
    <southEastHexNumber>0409</southEastHexNumber>
    <southHexNumber>0310</southHexNumber>
    <southWestHexNumber>0209</southWestHexNumber>
    <northWestHexNumber>0208</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0310</hexNumber>
    <northHexNumber>0309</northHexNumber>
    <northEastHexNumber>0409</northEastHexNumber>
    <southEastHexNumber>0410</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0209</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0402</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0502</northEastHexNumber>
    <southEastHexNumber>0503</southEastHexNumber>
    <southHexNumber>0403</southHexNumber>
    <southWestHexNumber>0303</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0403</hexNumber>
    <northHexNumber>0402</northHexNumber>
    <northEastHexNumber>0503</northEastHexNumber>
    <southEastHexNumber>0504</southEastHexNumber>
    <southHexNumber>0404</southHexNumber>
    <southWestHexNumber>0304</southWestHexNumber>
    <northWestHexNumber>0303</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0404</hexNumber>
    <northHexNumber>0403</northHexNumber>
    <northEastHexNumber>0504</northEastHexNumber>
    <southEastHexNumber>0505</southEastHexNumber>
    <southHexNumber>0405</southHexNumber>
    <southWestHexNumber>0305</southWestHexNumber>
    <northWestHexNumber>0304</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0405</hexNumber>
    <northHexNumber>0404</northHexNumber>
    <northEastHexNumber>0505</northEastHexNumber>
    <southEastHexNumber>0506</southEastHexNumber>
    <southHexNumber>0406</southHexNumber>
    <southWestHexNumber>0306</southWestHexNumber>
    <northWestHexNumber>0305</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0406</hexNumber>
    <northHexNumber>0405</northHexNumber>
    <northEastHexNumber>0506</northEastHexNumber>
    <southEastHexNumber>0507</southEastHexNumber>
    <southHexNumber>0407</southHexNumber>
    <southWestHexNumber>0307</southWestHexNumber>
    <northWestHexNumber>0306</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0407</hexNumber>
    <northHexNumber>0406</northHexNumber>
    <northEastHexNumber>0507</northEastHexNumber>
    <southEastHexNumber>0508</southEastHexNumber>
    <southHexNumber>0408</southHexNumber>
    <southWestHexNumber>0308</southWestHexNumber>
    <northWestHexNumber>0307</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0408</hexNumber>
    <northHexNumber>0407</northHexNumber>
    <northEastHexNumber>0508</northEastHexNumber>
    <southEastHexNumber>0509</southEastHexNumber>
    <southHexNumber>0409</southHexNumber>
    <southWestHexNumber>0309</southWestHexNumber>
    <northWestHexNumber>0308</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0409</hexNumber>
    <northHexNumber>0408</northHexNumber>
    <northEastHexNumber>0509</northEastHexNumber>
    <southEastHexNumber>0510</southEastHexNumber>
    <southHexNumber>0410</southHexNumber>
    <southWestHexNumber>0310</southWestHexNumber>
    <northWestHexNumber>0309</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0410</hexNumber>
    <northHexNumber>0409</northHexNumber>
    <northEastHexNumber>0510</northEastHexNumber>
    <southEastHexNumber>0511</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0310</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0502</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0601</northEastHexNumber>
    <southEastHexNumber>0602</southEastHexNumber>
    <southHexNumber>0503</southHexNumber>
    <southWestHexNumber>0402</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0503</hexNumber>
    <northHexNumber>0502</northHexNumber>
    <northEastHexNumber>0602</northEastHexNumber>
    <southEastHexNumber>0603</southEastHexNumber>
    <southHexNumber>0504</southHexNumber>
    <southWestHexNumber>0403</southWestHexNumber>
    <northWestHexNumber>0402</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0504</hexNumber>
    <northHexNumber>0503</northHexNumber>
    <northEastHexNumber>0603</northEastHexNumber>
    <southEastHexNumber>0604</southEastHexNumber>
    <southHexNumber>0505</southHexNumber>
    <southWestHexNumber>0404</southWestHexNumber>
    <northWestHexNumber>0403</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0505</hexNumber>
    <northHexNumber>0504</northHexNumber>
    <northEastHexNumber>0604</northEastHexNumber>
    <southEastHexNumber>0605</southEastHexNumber>
    <southHexNumber>0506</southHexNumber>
    <southWestHexNumber>0405</southWestHexNumber>
    <northWestHexNumber>0404</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0506</hexNumber>
    <northHexNumber>0505</northHexNumber>
    <northEastHexNumber>0605</northEastHexNumber>
    <southEastHexNumber>0606</southEastHexNumber>
    <southHexNumber>0507</southHexNumber>
    <southWestHexNumber>0406</southWestHexNumber>
    <northWestHexNumber>0405</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0507</hexNumber>
    <northHexNumber>0506</northHexNumber>
    <northEastHexNumber>0606</northEastHexNumber>
    <southEastHexNumber>0607</southEastHexNumber>
    <southHexNumber>0508</southHexNumber>
    <southWestHexNumber>0407</southWestHexNumber>
    <northWestHexNumber>0406</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0508</hexNumber>
    <northHexNumber>0507</northHexNumber>
    <northEastHexNumber>0607</northEastHexNumber>
    <southEastHexNumber>0608</southEastHexNumber>
    <southHexNumber>0509</southHexNumber>
    <southWestHexNumber>0408</southWestHexNumber>
    <northWestHexNumber>0407</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0509</hexNumber>
    <northHexNumber>0508</northHexNumber>
    <northEastHexNumber>0608</northEastHexNumber>
    <southEastHexNumber>0609</southEastHexNumber>
    <southHexNumber>0510</southHexNumber>
    <southWestHexNumber>0409</southWestHexNumber>
    <northWestHexNumber>0408</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0510</hexNumber>
    <northHexNumber>0509</northHexNumber>
    <northEastHexNumber>0609</northEastHexNumber>
    <southEastHexNumber>0610</southEastHexNumber>
    <southHexNumber>0511</southHexNumber>
    <southWestHexNumber>0410</southWestHexNumber>
    <northWestHexNumber>0409</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0511</hexNumber>
    <northHexNumber>0510</northHexNumber>
    <northEastHexNumber>0610</northEastHexNumber>
    <southEastHexNumber>0611</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0410</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0601</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0</northEastHexNumber>
    <southEastHexNumber>0702</southEastHexNumber>
    <southHexNumber>0602</southHexNumber>
    <southWestHexNumber>0502</southWestHexNumber>
    <northWestHexNumber>0</northWestHexNumber>
    <specialHex>1</specialHex>
  </hex>
  <hex>
    <hexNumber>0602</hexNumber>
    <northHexNumber>0601</northHexNumber>
    <northEastHexNumber>0702</northEastHexNumber>
    <southEastHexNumber>0703</southEastHexNumber>
    <southHexNumber>0603</southHexNumber>
    <southWestHexNumber>0503</southWestHexNumber>
    <northWestHexNumber>0502</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0603</hexNumber>
    <northHexNumber>0602</northHexNumber>
    <northEastHexNumber>0703</northEastHexNumber>
    <southEastHexNumber>0704</southEastHexNumber>
    <southHexNumber>0604</southHexNumber>
    <southWestHexNumber>0504</southWestHexNumber>
    <northWestHexNumber>0503</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0604</hexNumber>
    <northHexNumber>0603</northHexNumber>
    <northEastHexNumber>0704</northEastHexNumber>
    <southEastHexNumber>0705</southEastHexNumber>
    <southHexNumber>0605</southHexNumber>
    <southWestHexNumber>0505</southWestHexNumber>
    <northWestHexNumber>0504</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0605</hexNumber>
    <northHexNumber>0604</northHexNumber>
    <northEastHexNumber>0705</northEastHexNumber>
    <southEastHexNumber>0706</southEastHexNumber>
    <southHexNumber>0606</southHexNumber>
    <southWestHexNumber>0506</southWestHexNumber>
    <northWestHexNumber>0505</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0606</hexNumber>
    <northHexNumber>0605</northHexNumber>
    <northEastHexNumber>0706</northEastHexNumber>
    <southEastHexNumber>0707</southEastHexNumber>
    <southHexNumber>0607</southHexNumber>
    <southWestHexNumber>0507</southWestHexNumber>
    <northWestHexNumber>0506</northWestHexNumber>
    <specialHex>2</specialHex>
  </hex>
  <hex>
    <hexNumber>0607</hexNumber>
    <northHexNumber>0606</northHexNumber>
    <northEastHexNumber>0707</northEastHexNumber>
    <southEastHexNumber>0708</southEastHexNumber>
    <southHexNumber>0608</southHexNumber>
    <southWestHexNumber>0508</southWestHexNumber>
    <northWestHexNumber>0507</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0608</hexNumber>
    <northHexNumber>0607</northHexNumber>
    <northEastHexNumber>0708</northEastHexNumber>
    <southEastHexNumber>0709</southEastHexNumber>
    <southHexNumber>0609</southHexNumber>
    <southWestHexNumber>0509</southWestHexNumber>
    <northWestHexNumber>0508</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0609</hexNumber>
    <northHexNumber>0608</northHexNumber>
    <northEastHexNumber>0709</northEastHexNumber>
    <southEastHexNumber>0710</southEastHexNumber>
    <southHexNumber>0610</southHexNumber>
    <southWestHexNumber>0510</southWestHexNumber>
    <northWestHexNumber>0509</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0610</hexNumber>
    <northHexNumber>0609</northHexNumber>
    <northEastHexNumber>0710</northEastHexNumber>
    <southEastHexNumber>0711</southEastHexNumber>
    <southHexNumber>0611</southHexNumber>
    <southWestHexNumber>0511</southWestHexNumber>
    <northWestHexNumber>0510</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0611</hexNumber>
    <northHexNumber>0610</northHexNumber>
    <northEastHexNumber>0711</northEastHexNumber>
    <southEastHexNumber>0</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0</southWestHexNumber>
    <northWestHexNumber>0511</northWestHexNumber>
    <specialHex>1</specialHex>
  </hex>
  <hex>
    <hexNumber>0702</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0</northEastHexNumber>
    <southEastHexNumber>0802</southEastHexNumber>
    <southHexNumber>0703</southHexNumber>
    <southWestHexNumber>0602</southWestHexNumber>
    <northWestHexNumber>0601</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0703</hexNumber>
    <northHexNumber>0702</northHexNumber>
    <northEastHexNumber>0802</northEastHexNumber>
    <southEastHexNumber>0803</southEastHexNumber>
    <southHexNumber>0704</southHexNumber>
    <southWestHexNumber>0603</southWestHexNumber>
    <northWestHexNumber>0602</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0704</hexNumber>
    <northHexNumber>0703</northHexNumber>
    <northEastHexNumber>0803</northEastHexNumber>
    <southEastHexNumber>0804</southEastHexNumber>
    <southHexNumber>0705</southHexNumber>
    <southWestHexNumber>0604</southWestHexNumber>
    <northWestHexNumber>0603</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0705</hexNumber>
    <northHexNumber>0704</northHexNumber>
    <northEastHexNumber>0804</northEastHexNumber>
    <southEastHexNumber>0805</southEastHexNumber>
    <southHexNumber>0706</southHexNumber>
    <southWestHexNumber>0605</southWestHexNumber>
    <northWestHexNumber>0604</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0706</hexNumber>
    <northHexNumber>0705</northHexNumber>
    <northEastHexNumber>0805</northEastHexNumber>
    <southEastHexNumber>0806</southEastHexNumber>
    <southHexNumber>0707</southHexNumber>
    <southWestHexNumber>0606</southWestHexNumber>
    <northWestHexNumber>0605</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0707</hexNumber>
    <northHexNumber>0706</northHexNumber>
    <northEastHexNumber>0806</northEastHexNumber>
    <southEastHexNumber>0807</southEastHexNumber>
    <southHexNumber>0708</southHexNumber>
    <southWestHexNumber>0607</southWestHexNumber>
    <northWestHexNumber>0606</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0708</hexNumber>
    <northHexNumber>0707</northHexNumber>
    <northEastHexNumber>0807</northEastHexNumber>
    <southEastHexNumber>0808</southEastHexNumber>
    <southHexNumber>0709</southHexNumber>
    <southWestHexNumber>0608</southWestHexNumber>
    <northWestHexNumber>0607</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0709</hexNumber>
    <northHexNumber>0708</northHexNumber>
    <northEastHexNumber>0808</northEastHexNumber>
    <southEastHexNumber>0809</southEastHexNumber>
    <southHexNumber>0710</southHexNumber>
    <southWestHexNumber>0609</southWestHexNumber>
    <northWestHexNumber>0608</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0710</hexNumber>
    <northHexNumber>0709</northHexNumber>
    <northEastHexNumber>0809</northEastHexNumber>
    <southEastHexNumber>0810</southEastHexNumber>
    <southHexNumber>0711</southHexNumber>
    <southWestHexNumber>0610</southWestHexNumber>
    <northWestHexNumber>0609</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0711</hexNumber>
    <northHexNumber>0710</northHexNumber>
    <northEastHexNumber>0810</northEastHexNumber>
    <southEastHexNumber>0</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0611</southWestHexNumber>
    <northWestHexNumber>0610</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0802</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0</northEastHexNumber>
    <southEastHexNumber>0903</southEastHexNumber>
    <southHexNumber>0803</southHexNumber>
    <southWestHexNumber>0703</southWestHexNumber>
    <northWestHexNumber>0702</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0803</hexNumber>
    <northHexNumber>0802</northHexNumber>
    <northEastHexNumber>0903</northEastHexNumber>
    <southEastHexNumber>0904</southEastHexNumber>
    <southHexNumber>0804</southHexNumber>
    <southWestHexNumber>0704</southWestHexNumber>
    <northWestHexNumber>0703</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0804</hexNumber>
    <northHexNumber>0803</northHexNumber>
    <northEastHexNumber>0904</northEastHexNumber>
    <southEastHexNumber>0905</southEastHexNumber>
    <southHexNumber>0805</southHexNumber>
    <southWestHexNumber>0705</southWestHexNumber>
    <northWestHexNumber>0704</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0805</hexNumber>
    <northHexNumber>0804</northHexNumber>
    <northEastHexNumber>0905</northEastHexNumber>
    <southEastHexNumber>0906</southEastHexNumber>
    <southHexNumber>0806</southHexNumber>
    <southWestHexNumber>0706</southWestHexNumber>
    <northWestHexNumber>0705</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0806</hexNumber>
    <northHexNumber>0805</northHexNumber>
    <northEastHexNumber>0906</northEastHexNumber>
    <southEastHexNumber>0907</southEastHexNumber>
    <southHexNumber>0807</southHexNumber>
    <southWestHexNumber>0707</southWestHexNumber>
    <northWestHexNumber>0706</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0807</hexNumber>
    <northHexNumber>0806</northHexNumber>
    <northEastHexNumber>0907</northEastHexNumber>
    <southEastHexNumber>0908</southEastHexNumber>
    <southHexNumber>0808</southHexNumber>
    <southWestHexNumber>0708</southWestHexNumber>
    <northWestHexNumber>0707</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0808</hexNumber>
    <northHexNumber>0807</northHexNumber>
    <northEastHexNumber>0908</northEastHexNumber>
    <southEastHexNumber>0909</southEastHexNumber>
    <southHexNumber>0809</southHexNumber>
    <southWestHexNumber>0709</southWestHexNumber>
    <northWestHexNumber>0708</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0809</hexNumber>
    <northHexNumber>0808</northHexNumber>
    <northEastHexNumber>0909</northEastHexNumber>
    <southEastHexNumber>0910</southEastHexNumber>
    <southHexNumber>0810</southHexNumber>
    <southWestHexNumber>0710</southWestHexNumber>
    <northWestHexNumber>0709</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0810</hexNumber>
    <northHexNumber>0809</northHexNumber>
    <northEastHexNumber>0910</northEastHexNumber>
    <southEastHexNumber>0</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0711</southWestHexNumber>
    <northWestHexNumber>0710</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0903</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0</northEastHexNumber>
    <southEastHexNumber>1003</southEastHexNumber>
    <southHexNumber>0904</southHexNumber>
    <southWestHexNumber>0803</southWestHexNumber>
    <northWestHexNumber>0802</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0904</hexNumber>
    <northHexNumber>0903</northHexNumber>
    <northEastHexNumber>1003</northEastHexNumber>
    <southEastHexNumber>1004</southEastHexNumber>
    <southHexNumber>0905</southHexNumber>
    <southWestHexNumber>0804</southWestHexNumber>
    <northWestHexNumber>0803</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0905</hexNumber>
    <northHexNumber>0904</northHexNumber>
    <northEastHexNumber>1004</northEastHexNumber>
    <southEastHexNumber>1005</southEastHexNumber>
    <southHexNumber>0906</southHexNumber>
    <southWestHexNumber>0805</southWestHexNumber>
    <northWestHexNumber>0804</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0906</hexNumber>
    <northHexNumber>0905</northHexNumber>
    <northEastHexNumber>1005</northEastHexNumber>
    <southEastHexNumber>1006</southEastHexNumber>
    <southHexNumber>0907</southHexNumber>
    <southWestHexNumber>0806</southWestHexNumber>
    <northWestHexNumber>0805</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0907</hexNumber>
    <northHexNumber>0906</northHexNumber>
    <northEastHexNumber>1006</northEastHexNumber>
    <southEastHexNumber>1007</southEastHexNumber>
    <southHexNumber>0908</southHexNumber>
    <southWestHexNumber>0807</southWestHexNumber>
    <northWestHexNumber>0806</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0908</hexNumber>
    <northHexNumber>0907</northHexNumber>
    <northEastHexNumber>1007</northEastHexNumber>
    <southEastHexNumber>1008</southEastHexNumber>
    <southHexNumber>0909</southHexNumber>
    <southWestHexNumber>0808</southWestHexNumber>
    <northWestHexNumber>0807</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0909</hexNumber>
    <northHexNumber>0908</northHexNumber>
    <northEastHexNumber>1008</northEastHexNumber>
    <southEastHexNumber>1009</southEastHexNumber>
    <southHexNumber>0910</southHexNumber>
    <southWestHexNumber>0809</southWestHexNumber>
    <northWestHexNumber>0808</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>0910</hexNumber>
    <northHexNumber>0909</northHexNumber>
    <northEastHexNumber>1009</northEastHexNumber>
    <southEastHexNumber>0</southEastHexNumber>
    <southHexNumber>0</southHexNumber>
    <southWestHexNumber>0810</southWestHexNumber>
    <northWestHexNumber>0809</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>1003</hexNumber>
    <northHexNumber>0</northHexNumber>
    <northEastHexNumber>0</northEastHexNumber>
    <southEastHexNumber>1104</southEastHexNumber>
    <southHexNumber>1004</southHexNumber>
    <southWestHexNumber>0904</southWestHexNumber>
    <northWestHexNumber>0903</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>1004</hexNumber>
    <northHexNumber>1003</northHexNumber>
    <northEastHexNumber>1104</northEastHexNumber>
    <southEastHexNumber>1105</southEastHexNumber>
    <southHexNumber>1005</southHexNumber>
    <southWestHexNumber>0905</southWestHexNumber>
    <northWestHexNumber>0904</northWestHexNumber>
    <specialHex>0</specialHex>
  </hex>
  <hex>
    <hexNumber>1005</hexNumber>
    <northHexNumber>1004</northHexNumber>
    <northEastHexNumber>1105</northEastHexNumber>
    <southEastHexNumber>1106</southEastHexNumber>
    <southHexNumber>1006</southHexNumber>
    <southWestHexNumber>0906</southWestHexNumber>
    <northWestHexNumber>0905</northWestHexNumber>