<?xml version="1.0" encoding="UTF-8"?>
<!--
  This file was generated by MainMapBuilderForm.java

  Author: David Klingenberg
  Generated on: 2014/04/11 19:33:10
-->


<!DOCTYPE map [
  <!ELEMENT map (hex*)>
  <!ELEMENT hex (hexNumber, northHexNumber, northEastHexNumber,
                 southEastHexNumber, southHexNumber, southWestHexNumber,
                 northWestHexNumber, terrainKey, provinceName, cityHex?,
                 vortexHex?, portalHex?, hexEdgeMap?, castleHex?, hexName?,
                 capitalHex?, townHex?)>
  <!ELEMENT capitalHex (#PCDATA)>
  <!ELEMENT townHex (#PCDATA)>
  <!ELEMENT hexName (#PCDATA)>
  <!ELEMENT hexNumber (#PCDATA)>
  <!ELEMENT northHexNumber (#PCDATA)>
  <!ELEMENT northEastHexNumber (#PCDATA)>
  <!ELEMENT southEastHexNumber (#PCDATA)>
  <!ELEMENT southHexNumber (#PCDATA)>
  <!ELEMENT southWestHexNumber (#PCDATA)>
  <!ELEMENT northWestHexNumber (#PCDATA)>
  <!ELEMENT terrainKey (#PCDATA)>
  <!ELEMENT provinceName (#PCDATA)>
  <!ELEMENT cityHex (#PCDATA)>
  <!ELEMENT vortexHex (#PCDATA)>
  <!ELEMENT portalHex (#PCDATA)>
  <!ELEMENT castleHex (#PCDATA)>
  <!ELEMENT hexEdgeMap (northEdge?, northEastEdge?, southEastEdge?,
                           southEdge?, southWestEdge?, northWestEdge?) >
    <!ELEMENT northEdge (edgeAttribute+)>
    <!ELEMENT northEastEdge (edgeAttribute+)>
    <!ELEMENT southEastEdge (edgeAttribute+)>
    <!ELEMENT southEdge (edgeAttribute+)>
    <!ELEMENT southWestEdge (edgeAttribute+)>
    <!ELEMENT northWestEdge (edgeAttribute+)>
        <!ELEMENT edgeAttribute (#PCDATA)>
]>

<map>
    <hex>
        <hexNumber>1411</hexNumber>
        <northHexNumber>1410</northHexNumber>
        <northEastHexNumber>1511</northEastHexNumber>
        <southEastHexNumber>1512</southEastHexNumber>
        <southHexNumber>1412</southHexNumber>
        <southWestHexNumber>1312</southWestHexNumber>
        <northWestHexNumber>1311</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1410</hexNumber>
        <northHexNumber>1409</northHexNumber>
        <northEastHexNumber>1510</northEastHexNumber>
        <southEastHexNumber>1511</southEastHexNumber>
        <southHexNumber>1411</southHexNumber>
        <southWestHexNumber>1311</southWestHexNumber>
        <northWestHexNumber>1310</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1415</hexNumber>
        <northHexNumber>1414</northHexNumber>
        <northEastHexNumber>1515</northEastHexNumber>
        <southEastHexNumber>1516</southEastHexNumber>
        <southHexNumber>1416</southHexNumber>
        <southWestHexNumber>1316</southWestHexNumber>
        <northWestHexNumber>1315</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Ithilgil</provinceName>
        
        <hexEdgeMap>
          <southEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEastEdge>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1414</hexNumber>
        <northHexNumber>1413</northHexNumber>
        <northEastHexNumber>1514</northEastHexNumber>
        <southEastHexNumber>1515</southEastHexNumber>
        <southHexNumber>1415</southHexNumber>
        <southWestHexNumber>1315</southWestHexNumber>
        <northWestHexNumber>1314</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Ithilgil</provinceName>
        
    </hex>
    <hex>
        <hexNumber>0709</hexNumber>
        <northHexNumber>0708</northHexNumber>
        <northEastHexNumber>0808</northEastHexNumber>
        <southEastHexNumber>0809</southEastHexNumber>
        <southHexNumber>0710</southHexNumber>
        <southWestHexNumber>0609</southWestHexNumber>
        <northWestHexNumber>0608</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </northEdge>
          <southEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1413</hexNumber>
        <northHexNumber>1412</northHexNumber>
        <northEastHexNumber>1513</northEastHexNumber>
        <southEastHexNumber>1514</southEastHexNumber>
        <southHexNumber>1414</southHexNumber>
        <southWestHexNumber>1314</southWestHexNumber>
        <northWestHexNumber>1313</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <southEastEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </southEastEdge>
          <northWestEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1412</hexNumber>
        <northHexNumber>1411</northHexNumber>
        <northEastHexNumber>1512</northEastHexNumber>
        <southEastHexNumber>1513</southEastHexNumber>
        <southHexNumber>1413</southHexNumber>
        <southWestHexNumber>1313</southWestHexNumber>
        <northWestHexNumber>1312</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1419</hexNumber>
        <northHexNumber>1418</northHexNumber>
        <northEastHexNumber>1519</northEastHexNumber>
        <southEastHexNumber>1520</southEastHexNumber>
        <southHexNumber>1420</southHexNumber>
        <southWestHexNumber>1320</southWestHexNumber>
        <northWestHexNumber>1319</northWestHexNumber>
        <terrainKey>D</terrainKey>
        <provinceName>Outer Krasnia</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEastEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1418</hexNumber>
        <northHexNumber>1417</northHexNumber>
        <northEastHexNumber>1518</northEastHexNumber>
        <southEastHexNumber>1519</southEastHexNumber>
        <southHexNumber>1419</southHexNumber>
        <southWestHexNumber>1319</southWestHexNumber>
        <northWestHexNumber>1318</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Dwarfhaven</provinceName>
        
        <hexEdgeMap>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1417</hexNumber>
        <northHexNumber>1416</northHexNumber>
        <northEastHexNumber>1517</northEastHexNumber>
        <southEastHexNumber>1518</southEastHexNumber>
        <southHexNumber>1418</southHexNumber>
        <southWestHexNumber>1318</southWestHexNumber>
        <northWestHexNumber>1317</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Dwarfhaven</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1416</hexNumber>
        <northHexNumber>1415</northHexNumber>
        <northEastHexNumber>1516</northEastHexNumber>
        <southEastHexNumber>1517</southEastHexNumber>
        <southHexNumber>1417</southHexNumber>
        <southWestHexNumber>1317</southWestHexNumber>
        <northWestHexNumber>1316</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Dwarfhaven</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1821</hexNumber>
        <northHexNumber>1820</northHexNumber>
        <northEastHexNumber>1921</northEastHexNumber>
        <southEastHexNumber>1922</southEastHexNumber>
        <southHexNumber>1822</southHexNumber>
        <southWestHexNumber>1722</southWestHexNumber>
        <northWestHexNumber>1721</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Dwarfhaven</provinceName>
        <hexEdgeMap>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1822</hexNumber>
        <northHexNumber>1821</northHexNumber>
        <northEastHexNumber>1922</northEastHexNumber>
        <southEastHexNumber>1923</southEastHexNumber>
        <southHexNumber>1823</southHexNumber>
        <southWestHexNumber>1723</southWestHexNumber>
        <northWestHexNumber>1722</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEastEdge>
          <northWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1820</hexNumber>
        <northHexNumber>1819</northHexNumber>
        <northEastHexNumber>1920</northEastHexNumber>
        <southEastHexNumber>1921</southEastHexNumber>
        <southHexNumber>1821</southHexNumber>
        <southWestHexNumber>1721</southWestHexNumber>
        <northWestHexNumber>1720</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Dwarfhaven</provinceName>
    </hex>
    <hex>
        <hexNumber>1825</hexNumber>
        <northHexNumber>1824</northHexNumber>
        <northEastHexNumber>1925</northEastHexNumber>
        <southEastHexNumber>1926</southEastHexNumber>
        <southHexNumber>1826</southHexNumber>
        <southWestHexNumber>1726</southWestHexNumber>
        <northWestHexNumber>1725</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0708</hexNumber>
        <northHexNumber>0707</northHexNumber>
        <northEastHexNumber>0807</northEastHexNumber>
        <southEastHexNumber>0808</southEastHexNumber>
        <southHexNumber>0709</southHexNumber>
        <southWestHexNumber>0608</southWestHexNumber>
        <northWestHexNumber>0607</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </northEdge>
          <southEastEdge>
            <edgeAttribute>Rd</edgeAttribute>
            <edgeAttribute>Tr</edgeAttribute>
          </southEastEdge>
          <southEdge>
            <edgeAttribute>Rd</edgeAttribute>
            <edgeAttribute>Tr</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1826</hexNumber>
        <northHexNumber>1825</northHexNumber>
        <northEastHexNumber>1926</northEastHexNumber>
        <southEastHexNumber>1927</southEastHexNumber>
        <southHexNumber>1827</southHexNumber>
        <southWestHexNumber>1727</southWestHexNumber>
        <northWestHexNumber>1726</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
        <hexEdgeMap>
          <northEastEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </northEastEdge>
          <southWestEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </southWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>0707</hexNumber>
        <northHexNumber>0706</northHexNumber>
        <northEastHexNumber>0806</northEastHexNumber>
        <southEastHexNumber>0807</southEastHexNumber>
        <southHexNumber>0708</southHexNumber>
        <southWestHexNumber>0607</southWestHexNumber>
        <northWestHexNumber>0606</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </northEdge>
          <southEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1823</hexNumber>
        <northHexNumber>1822</northHexNumber>
        <northEastHexNumber>1923</northEastHexNumber>
        <southEastHexNumber>1924</southEastHexNumber>
        <southHexNumber>1824</southHexNumber>
        <southWestHexNumber>1724</southWestHexNumber>
        <northWestHexNumber>1723</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0706</hexNumber>
        <northHexNumber>0705</northHexNumber>
        <northEastHexNumber>0805</northEastHexNumber>
        <southEastHexNumber>0806</southEastHexNumber>
        <southHexNumber>0707</southHexNumber>
        <southWestHexNumber>0606</southWestHexNumber>
        <northWestHexNumber>0605</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
            <edgeAttribute>Br</edgeAttribute>
            <edgeAttribute>Rd</edgeAttribute>
          </northEastEdge>
          <southEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1824</hexNumber>
        <northHexNumber>1823</northHexNumber>
        <northEastHexNumber>1924</northEastHexNumber>
        <southEastHexNumber>1925</southEastHexNumber>
        <southHexNumber>1825</southHexNumber>
        <southWestHexNumber>1725</southWestHexNumber>
        <northWestHexNumber>1724</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0705</hexNumber>
        <northHexNumber>0704</northHexNumber>
        <northEastHexNumber>0804</northEastHexNumber>
        <southEastHexNumber>0805</southEastHexNumber>
        <southHexNumber>0706</southHexNumber>
        <southWestHexNumber>0605</southWestHexNumber>
        <northWestHexNumber>0604</northWestHexNumber>
        <terrainKey>Mrl</terrainKey>
        <provinceName>Citadel of Blood</provinceName>
        
        <hexEdgeMap>
          <northEastEdge>
            <edgeAttribute>Wa</edgeAttribute>
          </northEastEdge>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
          <northWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1829</hexNumber>
        <northHexNumber>1828</northHexNumber>
        <northEastHexNumber>1929</northEastHexNumber>
        <southEastHexNumber>1930</southEastHexNumber>
        <southHexNumber>1830</southHexNumber>
        <southWestHexNumber>1730</southWestHexNumber>
        <northWestHexNumber>1729</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0704</hexNumber>
        <northHexNumber>0703</northHexNumber>
        <northEastHexNumber>0803</northEastHexNumber>
        <southEastHexNumber>0804</southEastHexNumber>
        <southHexNumber>0705</southHexNumber>
        <southWestHexNumber>0604</southWestHexNumber>
        <northWestHexNumber>0603</northWestHexNumber>
        <terrainKey>Mrl</terrainKey>
        <provinceName>Citadel of Blood</provinceName>
        
        <hexEdgeMap>
          <northEastEdge>
            <edgeAttribute>Wa</edgeAttribute>
          </northEastEdge>
          <southEastEdge>
            <edgeAttribute>Wa</edgeAttribute>
          </southEastEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
          <northWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>0703</hexNumber>
        <northHexNumber>0702</northHexNumber>
        <northEastHexNumber>0802</northEastHexNumber>
        <southEastHexNumber>0803</southEastHexNumber>
        <southHexNumber>0704</southHexNumber>
        <southWestHexNumber>0603</southWestHexNumber>
        <northWestHexNumber>0602</northWestHexNumber>
        <terrainKey>Mrl</terrainKey>
        <provinceName>Citadel of Blood</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <southEastEdge>
            <edgeAttribute>Wa</edgeAttribute>
          </southEastEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
          <northWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1827</hexNumber>
        <northHexNumber>1826</northHexNumber>
        <northEastHexNumber>1927</northEastHexNumber>
        <southEastHexNumber>1928</southEastHexNumber>
        <southHexNumber>1828</southHexNumber>
        <southWestHexNumber>1728</southWestHexNumber>
        <northWestHexNumber>1727</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0702</hexNumber>
        <northHexNumber>0701</northHexNumber>
        <northEastHexNumber>0801</northEastHexNumber>
        <southEastHexNumber>0802</southEastHexNumber>
        <southHexNumber>0703</southHexNumber>
        <southWestHexNumber>0602</southWestHexNumber>
        <northWestHexNumber>0601</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Kelgarnth</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1828</hexNumber>
        <northHexNumber>1827</northHexNumber>
        <northEastHexNumber>1928</northEastHexNumber>
        <southEastHexNumber>1929</southEastHexNumber>
        <southHexNumber>1829</southHexNumber>
        <southWestHexNumber>1729</southWestHexNumber>
        <northWestHexNumber>1728</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
    </hex>
    <hex>
        <hexNumber>0701</hexNumber>
        <northHexNumber>0000</northHexNumber>
        <northEastHexNumber>0000</northEastHexNumber>
        <southEastHexNumber>0801</southEastHexNumber>
        <southHexNumber>0702</southHexNumber>
        <southWestHexNumber>0601</southWestHexNumber>
        <northWestHexNumber>0000</northWestHexNumber>
        <terrainKey>R</terrainKey>
        <provinceName>Kelgarnth</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1420</hexNumber>
        <northHexNumber>1419</northHexNumber>
        <northEastHexNumber>1520</northEastHexNumber>
        <southEastHexNumber>1521</southEastHexNumber>
        <southHexNumber>1421</southHexNumber>
        <southWestHexNumber>1321</southWestHexNumber>
        <northWestHexNumber>1320</northWestHexNumber>
        <terrainKey>R</terrainKey>
        <provinceName>Outer Krasnia</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1422</hexNumber>
        <northHexNumber>1421</northHexNumber>
        <northEastHexNumber>1522</northEastHexNumber>
        <southEastHexNumber>1523</southEastHexNumber>
        <southHexNumber>1423</southHexNumber>
        <southWestHexNumber>1323</southWestHexNumber>
        <northWestHexNumber>1322</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Krasnia</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEastEdge>
          <southEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEastEdge>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1421</hexNumber>
        <northHexNumber>1420</northHexNumber>
        <northEastHexNumber>1521</northEastHexNumber>
        <southEastHexNumber>1522</southEastHexNumber>
        <southHexNumber>1422</southHexNumber>
        <southWestHexNumber>1322</southWestHexNumber>
        <northWestHexNumber>1321</northWestHexNumber>
        <terrainKey>R</terrainKey>
        <provinceName>Outer Krasnia</provinceName>
        
        <hexEdgeMap>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
          <southWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1424</hexNumber>
        <northHexNumber>1423</northHexNumber>
        <northEastHexNumber>1524</northEastHexNumber>
        <southEastHexNumber>1525</southEastHexNumber>
        <southHexNumber>1425</southHexNumber>
        <southWestHexNumber>1325</southWestHexNumber>
        <northWestHexNumber>1324</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1423</hexNumber>
        <northHexNumber>1422</northHexNumber>
        <northEastHexNumber>1523</northEastHexNumber>
        <southEastHexNumber>1524</southEastHexNumber>
        <southHexNumber>1424</southHexNumber>
        <southWestHexNumber>1324</southWestHexNumber>
        <northWestHexNumber>1323</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEdge>
          <northWestEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1426</hexNumber>
        <northHexNumber>1425</northHexNumber>
        <northEastHexNumber>1526</northEastHexNumber>
        <southEastHexNumber>1527</southEastHexNumber>
        <southHexNumber>1427</southHexNumber>
        <southWestHexNumber>1327</southWestHexNumber>
        <northWestHexNumber>1326</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1425</hexNumber>
        <northHexNumber>1424</northHexNumber>
        <northEastHexNumber>1525</northEastHexNumber>
        <southEastHexNumber>1526</southEastHexNumber>
        <southHexNumber>1426</southHexNumber>
        <southWestHexNumber>1326</southWestHexNumber>
        <northWestHexNumber>1325</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1428</hexNumber>
        <northHexNumber>1427</northHexNumber>
        <northEastHexNumber>1528</northEastHexNumber>
        <southEastHexNumber>1529</southEastHexNumber>
        <southHexNumber>1429</southHexNumber>
        <southWestHexNumber>1329</southWestHexNumber>
        <northWestHexNumber>1328</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
    </hex>
    <hex>
        <hexNumber>1427</hexNumber>
        <northHexNumber>1426</northHexNumber>
        <northEastHexNumber>1527</northEastHexNumber>
        <southEastHexNumber>1528</southEastHexNumber>
        <southHexNumber>1428</southHexNumber>
        <southWestHexNumber>1328</southWestHexNumber>
        <northWestHexNumber>1327</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
        <hexEdgeMap>
          <southEastEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </southEastEdge>
          <northWestEdge>
            <edgeAttribute>Tr</edgeAttribute>
          </northWestEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1429</hexNumber>
        <northHexNumber>1428</northHexNumber>
        <northEastHexNumber>1529</northEastHexNumber>
        <southEastHexNumber>1530</southEastHexNumber>
        <southHexNumber>1430</southHexNumber>
        <southWestHexNumber>1330</southWestHexNumber>
        <northWestHexNumber>1329</northWestHexNumber>
        <terrainKey>Cl</terrainKey>
        <provinceName>Neitherworld</provinceName>
        
    </hex>
    <hex>
        <hexNumber>0711</hexNumber>
        <northHexNumber>0710</northHexNumber>
        <northEastHexNumber>0810</northEastHexNumber>
        <southEastHexNumber>0811</southEastHexNumber>
        <southHexNumber>0712</southHexNumber>
        <southWestHexNumber>0611</southWestHexNumber>
        <northWestHexNumber>0610</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </northEdge>
          <southEastEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </southEastEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>0710</hexNumber>
        <northHexNumber>0709</northHexNumber>
        <northEastHexNumber>0809</northEastHexNumber>
        <southEastHexNumber>0810</southEastHexNumber>
        <southHexNumber>0711</southHexNumber>
        <southWestHexNumber>0610</southWestHexNumber>
        <northWestHexNumber>0609</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Intas</provinceName>
        
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </northEdge>
          <southEdge>
            <edgeAttribute>Rd</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1810</hexNumber>
        <northHexNumber>1809</northHexNumber>
        <northEastHexNumber>1910</northEastHexNumber>
        <southEastHexNumber>1911</southEastHexNumber>
        <southHexNumber>1811</southHexNumber>
        <southWestHexNumber>1711</southWestHexNumber>
        <northWestHexNumber>1710</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Ithilgil</provinceName>
        <hexEdgeMap>
          <northEdge>
            <edgeAttribute>Pb</edgeAttribute>
            <edgeAttribute>St</edgeAttribute>
          </northEdge>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
            <edgeAttribute>St</edgeAttribute>
          </northEastEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1811</hexNumber>
        <northHexNumber>1810</northHexNumber>
        <northEastHexNumber>1911</northEastHexNumber>
        <southEastHexNumber>1912</southEastHexNumber>
        <southHexNumber>1812</southHexNumber>
        <southWestHexNumber>1712</southWestHexNumber>
        <northWestHexNumber>1711</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Ithilgil</provinceName>
    </hex>
    <hex>
        <hexNumber>1812</hexNumber>
        <northHexNumber>1811</northHexNumber>
        <northEastHexNumber>1912</northEastHexNumber>
        <southEastHexNumber>1913</southEastHexNumber>
        <southHexNumber>1813</southHexNumber>
        <southWestHexNumber>1713</southWestHexNumber>
        <northWestHexNumber>1712</northWestHexNumber>
        <terrainKey>Bro</terrainKey>
        <provinceName>Ithilgil</provinceName>
    </hex>
    <hex>
        <hexNumber>0717</hexNumber>
        <northHexNumber>0716</northHexNumber>
        <northEastHexNumber>0816</northEastHexNumber>
        <southEastHexNumber>0817</southEastHexNumber>
        <southHexNumber>0718</southHexNumber>
        <southWestHexNumber>0617</southWestHexNumber>
        <northWestHexNumber>0616</northWestHexNumber>
        <terrainKey>Wo</terrainKey>
        <provinceName>Vynar</provinceName>
        
        <hexEdgeMap>
          <northEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </northEastEdge>
          <southEastEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEastEdge>
          <southEdge>
            <edgeAttribute>Pb</edgeAttribute>
          </southEdge>
        </hexEdgeMap>
    </hex>
    <hex>
        <hexNumber>1813</hexNumber>
        <northHexNumber>1812</northHexNumber>
        <northEastHexNumber>1913</northEastHexNumber>
        <southEastHexNumber>1914</southEastHexNumber>
        <southHexNumber>1814</southHexNumber>
        <southWestHexNumber>1714</southWestHexNumber>
        <northWestHexNumber>1713</northWestHexNumber>
        <terrainKey>Bro</terrainKey>